lint 실행 가능하도록 cd로 폴더 이동

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -69,7 +69,9 @@ jobs:
         run: npm install --legacy-peer-deps
 
       - name: Run ESLint
-        run: npm run lint
+        run: |
+          cd packages/assignment-6
+          npm run lint || echo "Linting failed"
         continue-on-error: true
         
       - name: Comment ESLint errors
